version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - PADDLE_ENV=${PADDLE_ENV}
      - PADDLE_CLIENT_TOKEN=${PADDLE_CLIENT_TOKEN}
      - PADDLE_SELLER_ID=${PADDLE_SELLER_ID}
      - PADDLE_API_KEY=${PADDLE_API_KEY}
      - PADDLE_WEBHOOK_KEY=${PADDLE_WEBHOOK_KEY}
      - NEXT_PUBLIC_VERCEL_URL=${NEXT_PUBLIC_VERCEL_URL}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
